# Generated by Django 3.0.8 on 2020-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='results', to='exams.Choice'),
        ),
        migrations.DeleteModel(
            name='ExamResultChoice',
        ),
    ]
