# Generated by Django 3.0.8 on 2020-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20201128_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='exams.Choice'),
        ),
    ]
