# Generated by Django 3.0.8 on 2020-12-05 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_auto_20201205_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='passed_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
