# Generated by Django 3.0.8 on 2020-12-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='next',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='previous',
        ),
        migrations.AlterField(
            model_name='problem',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='exams.Domain'),
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_problems', to='exams.Problem')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_problems', to='exams.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='attached',
            field=models.ManyToManyField(blank=True, related_name='_problem_attached_+', through='exams.ProblemAttachment', to='exams.Problem'),
        ),
    ]
