# Generated by Django 3.0.8 on 2020-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20201128_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='ExamTitle'),
        ),
    ]
