# Generated by Django 3.0.8 on 2020-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='ChoiceText'),
        ),
    ]
