# Generated by Django 3.0.8 on 2020-12-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20201205_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
        migrations.AddField(
            model_name='problem',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='exams.Question'),
        ),
    ]
