# Generated by Django 3.0.8 on 2020-12-01 16:17

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20201201_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamChoice',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choices', jsonfield.fields.JSONField()),
            ],
        ),
    ]
