# Generated by Django 3.0.8 on 2020-12-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20201229_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualProblemAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_target_problems', to='exams.Problem')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_source_problems', to='exams.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='actual_attached',
            field=models.ManyToManyField(blank=True, related_name='_problem_actual_attached_+', through='exams.ActualProblemAttachment', to='exams.Problem'),
        ),
    ]
