# Generated by Django 3.0.8 on 2020-12-01 18:38

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='examchoice',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examchoice',
            name='choices',
            field=jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
