# Generated by Django 3.0.8 on 2021-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examresult_response_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('expected', 'Expected'), ('real', 'Real')], default='expected', max_length=50),
        ),
    ]
