# Generated by Django 3.0.8 on 2021-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examresult_response_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
