# Generated by Django 3.0.8 on 2021-01-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_examresult_state'),
        ('exams', '0015_exam_mode'),
    ]

    operations = [
    ]
