version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file: .env
    command: 'sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./.env:/app/src/.env
      - ./:/app
    depends_on:
      - db

  queue:
    build: .
    restart: unless-stopped
    env_file: .env
    command: sh /entrypoint-queue.sh
    volumes:
      - ./.env:/app/src/.env
      - ./:/app

  beat:
    build: .
    restart: unless-stopped
    env_file: .env
    command: sh /entrypoint-beat.sh
    volumes:
      - ./.env:/app/src/.env
      - ./:/app

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db-data:
