# Generated by Django 3.0.8 on 2020-11-20 22:30

from django.db import migrations
from django.contrib.auth.models import Group


def insert_user_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Student')
    Group.objects.get_or_create(name='Teacher')
    Group.objects.get_or_create(name='Expert')


def remove_user_groups(apps, schema_editor):
    Group.objects.filter(name__in=['Student', 'Teacher', 'Expert']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(insert_user_groups,
                             reverse_code=remove_user_groups),
    ]
