name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3360:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install libmysqlclient
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev
      - name: Install dependencies
        run: |
          sudo apt-get purge python-pip
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
        env:
          DB_NAME: db
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3360
