name: Lint

on: [pull_request, push]

jobs:
  lint:
    steps:
      - uses: actions/checkout@v1
      - uses: a-b-r-o-w-n/eslint-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "testing-platform-client/src/**/*"
          extensions: ".js,.ts"
          working-directory: "./testing-platform-client"
          quiet: "false"